package com.example.kampus.ui.chat

data class ChatItem(
    val id: String,
    val name: String,
    val lastMessage: String,
    val lastMessageType: String = "message",
    val lastCallType: String = "",
    val lastCallStatus: String = "",
    val lastMessageSenderName: String = "",
    val timestamp: String,
    val unreadCount: Int = 0,
    val isOnline: Boolean = false,
    val avatarInitials: String = "",
    val avatarColor: Long = 0xFF3B82F6,
    val avatarEmoji: String = "👤",
    val profileImageUrl: String = "",
    val isPinned: Boolean = false,
    val isMuted: Boolean = false,
    val isArchived: Boolean = false,
    val otherUserId: String = "",
    val isLastMessageFromMe: Boolean = false,
    val lastMessageSenderId: String = "",
)

data class ChatStory(
    val id: String = "",
    val ownerId: String = "",
    val ownerName: String = "",
    val ownerAvatarEmoji: String = "👤",
    val ownerAvatarColor: Long = 0xFF3B82F6,
    val ownerProfileImageUrl: String = "",
    val note: String = "",
    val imageUrl: String = "",
    val storyType: String = "note",
    val overlayText: String = "",
    val overlayX: Float = 0f,
    val overlayY: Float = 0f,
    val overlayColor: Long = 0xFFFFFFFF,
    val createdAtMillis: Long = 0L,
    val createdAtLabel: String = "now",
    val isMine: Boolean = false,
)

data class StoryViewer(
    val userId: String = "",
    val userName: String = "",
    val userAvatarEmoji: String = "👤",
    val userProfileImageUrl: String = "",
    val viewedAtMillis: Long = 0L,
    val viewedAtLabel: String = "now",
)

data class ChatPreviewUiState(
    val chatId: String = "",
    val chatName: String = "",
    val profileImageUrl: String = "",
    val avatarEmoji: String = "👤",
    val timestamp: String = "",
    val isPinned: Boolean = false,
    val isMuted: Boolean = false,
    val isArchived: Boolean = false,
    val otherUserId: String = "",
    val isLoading: Boolean = false,
    val error: String? = null,
    val messages: List<Message> = emptyList(),
)

data class Message(
    val id: String = "",
    val remoteMessageId: String = "",
    val senderId: String = "",
    val receiverId: String = "",
    val text: String = "",
    val encryptedPayload: String = "",
    val iv: String = "",
    val encryptedKeyForSender: String = "",
    val encryptedKeyForRecipient: String = "",
    val encryptedKeyForSenderSha1: String = "",
    val encryptedKeyForRecipientSha1: String = "",
    val isEncrypted: Boolean = false,
    val mediaUrl: String = "",
    val mediaName: String = "",
    val mediaType: String = "",
    val voiceUrl: String = "",
    val voiceDuration: String = "",
    val storyId: String = "",
    val storyImage: String = "",
    val storyCaption: String = "",
    val storyReplyText: String = "",
    val storyOwnerId: String = "",
    val storyOwnerName: String = "",
    val storyThumbnail: String = "",
    val isStoryReply: Boolean = false,
    val timestamp: String = "",
    val timestampMillis: Long = 0L,
    val isSentByMe: Boolean = false,
    val isVoice: Boolean = false,
    val isCallInvite: Boolean = false,
    val callType: String = "",
    val callStatus: String = "",
    val isRead: Boolean = false,
    val isEdited: Boolean = false,
    val isLiveLocation: Boolean = false,
    val locationLatitude: Double = 0.0,
    val locationLongitude: Double = 0.0,
    val locationRemainingSeconds: Long = 0L,
    val hiddenTextFor: List<String> = emptyList(),
    val deletedForUsers: List<String> = emptyList(),
    val reactions: Map<String, List<String>> = emptyMap(),
    val seen: Boolean = false,
    val deliveryState: MessageDeliveryState = MessageDeliveryState.Sending,
)

enum class MessageDeliveryState {
    Sending,
    Delivered,
    Seen,
    Failed
}